# Numericial Python(Numpy) - Part 1

In [3]:
# de facto standard(사실상의 표준)
import numpy as np #이게 기본

In [4]:
a=[1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
list(map(lambda x:3*x,a))

[3, 6, 9]

In [7]:
b=np.array([1,2,3])
b*3

array([3, 6, 9])

## 1.Numpy Dimensional array

In [8]:
a=np.array([1,4,5,8],float)
a

array([1., 4., 5., 8.])

In [9]:
type(a)

numpy.ndarray

In [11]:
a.dtype, a.shape  #데이터 타입, 몇차원인지(행열)

(dtype('float64'), (4,))

In [14]:
b=np.array([[1,2,3],[4,5,6]])
b.shape
#넘파이는 하나의 데이터 타입만 배열에 넣을 수 있다 정수면 정수만 ,플롯이면 플롯

(2, 3)

## 2.Array shape

In [16]:
# Vector(1차원)
vec=np.array([1,4,5,8])
vec, vec.shape

(array([1, 4, 5, 8]), (4,))

In [18]:
#Matrix
matrix = np.array([[1,2,5,8], [2,3,4,9], [4,5,6,7]])
matrix,matrix.shape

(array([[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]),
 (3, 4))

In [23]:
#Tensor
tensor=np.arange(1,25).reshape(2,3,4)
tensor, tensor.shape

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 (2, 3, 4))

In [24]:
print(vec)
print(matrix)
print(tensor)

[1 4 5 8]
[[1 2 5 8]
 [2 3 4 9]
 [4 5 6 7]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [25]:
vec.shape,matrix.shape,tensor.shape

((4,), (3, 4), (2, 3, 4))

In [27]:
#원소의 개수(shape의 숫자의 곱)
vec.size,matrix.size,tensor.size

(4, 12, 24)

In [28]:
a=np.array([1,2,3],dtype=np.float32)
a

In [34]:
b=np.array([1,2,3],np.float32)
b

array([1., 2., 3.], dtype=float32)

In [35]:
c=np.array([1,2,3],np.int16)
c

array([1, 2, 3], dtype=int16)

### reshape

In [38]:
#reshpae 엘리먼트에 걔수는 동일하면서 array의 shape를 변경한다
matrix.shape


(3, 4)

In [40]:
matrix.reshape(12,)

array([1, 2, 5, 8, 2, 3, 4, 9, 4, 5, 6, 7])

In [41]:
matrix.reshape(4,3)

array([[1, 2, 5],
       [8, 2, 3],
       [4, 9, 4],
       [5, 6, 7]])

In [42]:
#size가 동일하면 얼마든지 reshape 가능, -1은 사이즈 자동으로 맞춰준다
matrix.reshape(-1,)

array([1, 2, 5, 8, 2, 3, 4, 9, 4, 5, 6, 7])

In [43]:
matrix.reshape(-1,3)

array([[1, 2, 5],
       [8, 2, 3],
       [4, 9, 4],
       [5, 6, 7]])

In [44]:
tensor.reshape(4,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [45]:
matrix.reshape(-1)

array([1, 2, 5, 8, 2, 3, 4, 9, 4, 5, 6, 7])

In [46]:
matrix.reshape(1,-1)

array([[1, 2, 5, 8, 2, 3, 4, 9, 4, 5, 6, 7]])

In [47]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [5],
       [8],
       [2],
       [3],
       [4],
       [9],
       [4],
       [5],
       [6],
       [7]])

### flatten
- 다차원을 1차원으로 변경

In [48]:
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [50]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

#dot product를 하려면 (1,x) (x,1) 이 되어야한다

## 3.Indexing & Slicing

In [53]:
matrix.shape
print(matrix, matrix.shape)

[[1 2 5 8]
 [2 3 4 9]
 [4 5 6 7]] (3, 4)


In [55]:
matrix[0][1],matrix[0,1]

(2, 2)

In [56]:
tensor[1][1][2]

19

In [57]:
b=np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [60]:
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [62]:
#1 3 9 11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [64]:
#X 앞에 3열, y 는 마지막열
X,y=b[::-1], b[:, -1]

In [69]:
X,y,b

(array([[12, 13, 14, 15],
        [ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]]),
 array([ 3,  7, 11, 15]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [73]:
x=b[:,0:3]
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])