# Bag of Words

## 1. Count vectorizer

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.'] #스트링의 리스트로 넘겨야하므로

In [3]:
cvector = CountVectorizer()

In [4]:
cvector.fit(corpus) #fit은 학습이다.
cvector.transform(corpus).toarray()# 변환

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [5]:
cvector.vocabulary_ #학습을 한 결과

{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}

In [7]:
output = cvector.fit_transform(corpus).toarray()
output

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [9]:
output.shape #2차원

(1, 6)

## 불용어제거

### 사용자가 정의한 불용어

In [10]:
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


### scikit-lear에서 제공하는 불용어

In [11]:
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


### nltk에서 제공하는 불용어

In [12]:
from nltk.corpus import stopwords
text=["Family is not an important thing. It's everything."]
sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [14]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key


In [15]:
get_word(2,vect.vocabulary_)

'important'

### N gram

In [27]:
text1 = ['Machine learning is fun and not boring']
text2 = ['Machine is boring and learning is not fun']

In [28]:
vector = CountVectorizer()
print(vector.fit_transform(text1).toarray(), vector.vocabulary_)

[[1 1 1 1 1 1 1]] {'machine': 5, 'learning': 4, 'is': 3, 'fun': 2, 'and': 0, 'not': 6, 'boring': 1}


In [29]:
vector = CountVectorizer()
print(vector.fit_transform(text2).toarray(), vector.vocabulary_)

[[1 1 1 2 1 1 1]] {'machine': 5, 'is': 3, 'boring': 1, 'and': 0, 'learning': 4, 'not': 6, 'fun': 2}


In [30]:
vector = CountVectorizer(ngram_range=(1,2))
print(vector.fit_transform(text1).toarray(), vector.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]] {'machine': 9, 'learning': 7, 'is': 5, 'fun': 3, 'and': 0, 'not': 11, 'boring': 2, 'machine learning': 10, 'learning is': 8, 'is fun': 6, 'fun and': 4, 'and not': 1, 'not boring': 12}


In [31]:
vector = CountVectorizer(ngram_range=(1,2))
print(vector.fit_transform(text2).toarray(), vector.vocabulary_)

[[1 1 1 1 1 2 1 1 1 1 1 1 1 1]] {'machine': 10, 'is': 5, 'boring': 2, 'and': 0, 'learning': 8, 'not': 12, 'fun': 4, 'machine is': 11, 'is boring': 6, 'boring and': 3, 'and learning': 1, 'learning is': 9, 'is not': 7, 'not fun': 13}


In [32]:
vector = CountVectorizer(ngram_range=(1,3), stop_words='english')
print(vector.fit_transform(text1).toarray(), vector.vocabulary_)

[[1 1 1 1 1 1 1 1 1]] {'machine': 6, 'learning': 3, 'fun': 1, 'boring': 0, 'machine learning': 7, 'learning fun': 4, 'fun boring': 2, 'machine learning fun': 8, 'learning fun boring': 5}


### DTM

In [33]:
corpus = [
    "you know I want your love",
    "i like you",
    "what shoud i do"
]
vector = CountVectorizer(ngram_range=(1,3), stop_words='english')
print(vector.fit_transform(corpus).toarray(),'\n' ,vector.vocabulary_)

[[1 1 1 0 1 0 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]] 
 {'know': 0, 'want': 6, 'love': 4, 'know want': 1, 'want love': 7, 'know want love': 2, 'like': 3, 'shoud': 5}


## TF-IDF Vectorizer

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray().round(2),'\n',tvect.vocabulary_)

[[0.   0.47 0.   0.47 0.   0.47 0.   0.36 0.47]
 [0.   0.   0.8  0.   0.   0.   0.   0.61 0.  ]
 [0.58 0.   0.   0.   0.58 0.   0.58 0.   0.  ]] 
 {'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'shoud': 4, 'do': 0}


In [37]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}