# DataFrame class
> 시리즈들의 모임

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052], 
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"], 
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [4]:
data = {
    "지역": ["수도권", "경상권", "수도권", "경상권"], 
    "2015": [9904312, 3448737, 2890451, 2466052], #열 데이터
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
#columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"] 
#
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index)# coulums 가 없으면 순서가 엉망이된다
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [5]:
data=np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [6]:
df.values

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
df.지역.values

array([ 0,  6, 12, 18])

In [8]:
df['2015'].values

array([ 1,  7, 13, 19])

In [9]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [10]:
df.index.name = '도시'
df.columns.name = ' 특성'
df

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                            
서울    0     1     2     3     4              5
부산    6     7     8     9    10             11
인천   12    13    14    15    16             17
대구   18    19    20    21    22             23

In [11]:
df.columns.name = ' 특성'
df.index.name = '도시'
df

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                            
서울    0     1     2     3     4              5
부산    6     7     8     9    10             11
인천   12    13    14    15    16             17
대구   18    19    20    21    22             23

In [12]:
# 전치
df.T

도시             서울  부산  인천  대구
 특성                          
지역              0   6  12  18
2015            1   7  13  19
2010            2   8  14  20
2005            3   9  15  21
2000            4  10  16  22
2010-2015 증가율   5  11  17  23

### 열 데이터의 갱신, 추가, 삭제

In [13]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052], #열 데이터
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"], 
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [14]:
#갱신
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [15]:
#열 추가
df['2020'] = [1,2,3,4]
df

지역     2015     2010     2005     2000  2010-2015 증가율  2020
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [16]:
#열 삭제
del df['2020']
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

## 열 인덱싱

In [17]:
df['지역'] #결과는 시리즈로 나온다

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [18]:
df[['지역','2015']] # 데이터 프레임으로 나온다

지역     2015
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [19]:
df[['지역']]  #결과 데이터 프레임

지역
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [20]:
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

## 행 인덱싱

In [21]:
df[:'서울'] # 슬라이싱 형태로 볼수 밖에 없다

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83

In [22]:
df[1:2]

지역     2015     2010     2005     2000  2010-2015 증가율
부산  경상권  3448737  3393191  3512547  3655437           1.63

In [23]:
df['부산':'인천']

지역     2015     2010     2005     2000  2010-2015 증가율
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [24]:
df.head(3) #앞에서 3줄 행인덱싱

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [25]:
df.head(3).tail(2)

지역     2015     2010     2005     2000  2010-2015 증가율
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

## 개별 데이터 인덱싱
> df[`열이름`][`행이름`] \
> 리스트와 반대

In [28]:
df['2015']['서울'], df['2015'][0]

(9904312, 9904312)

## 연습문제 4.1.3
> 다음 데이터프레임에서 지정하는 데이터를 뽑아내거나 처리하라.

(1) 모든 학생의 수학 점수를 시리즈로 나타낸다. 

(2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다. 

(3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다. 

(4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다. 

(5) 춘향의 점수를 데이터프레임으로 나타낸다. 

(6) 향단의 점수를 시리즈로 나타낸다. 

In [ ]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

### (1) 모든 학생의 수학 점수를 시리즈로 나타낸다. 

In [ ]:
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

### (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다. 

In [ ]:
df[['국어', '영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

### (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다. 

In [ ]:
df.values
np.mean(df.values, axis=1).round(1) #평균 구하기(넘파이배열형태로)

array([86.7, 73.3, 70. , 46.7])

In [ ]:
df['평균'] = np.mean(df.values, axis=1).round(1) #새로운 열 생성
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  40  70  46.7

In [ ]:
df.mean(axis=1) # 데이터 프레임 자체에도 평균이 있다

춘향    86.675
몽룡    73.325
향단    70.000
방자    46.675
dtype: float64

### (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.

In [ ]:
del df['평균'] 
df.영어[3] = 80 #외우기
df['평균'] = np.round(df.mean(axis=1),1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

### (5) 춘향의 점수를 데이터프레임으로 나타낸다.

In [ ]:
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df[:1] #슬라이싱

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df.head(1)

국어  영어  수학    평균
춘향  80  90  90  86.7

In [ ]:
df.T[['춘향']] # 배열형태로 넣어야 한다

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

### (6) 향단의 점수를 시리즈로 나타낸다. 

In [ ]:
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64